Repository wanted-luckyzzang/wanted-rakuten, pull requests merged in 2022-02, with the labels that each got.

#1 feat: ApiData type 추가
  src/types/apiDataType.ts
  src/types/index.ts
Labels: feat

#2 feat: SendType 추가
  src/types/apiDataType.ts
  src/types/index.ts
Labels: feat

#3 feat: session storage 관련 util 함수 추가
  src/App.tsx
  src/utils/index.ts
  src/utils/sessionStorage.ts
Labels: feat

#4 feat: createdAt최대값 구해주는 함수, apiData중에서 해당하는 key값만 뽑는 함수 추가
  src/utils/apiData.ts
Labels: feat

#5 Feat/utils
  src/utils/apiData.ts
  src/utils/index.ts
Labels: refactor, chore

#6 feat: LinkPage Data Binding
  src/App.tsx
  src/pages/LinkPage/index.tsx
  src/utils/formatData.ts
  src/utils/index.ts
Labels: feat

#8 Feat/utils
  src/utils/apiData.ts
Labels: fix

#10 refactor: detailPage api 데이터 바인딩
  src/App.tsx
  src/pages/DetailPage/index.tsx
Labels: refactor

#11 feat: util함수 추가
  src/utils/apiData.ts
  src/utils/formatData.ts
Labels: feat, refactor

#12 fix: 계산 착오 있던거 제대로 수정
  src/utils/formatData.ts
Labels: fix

#14 feat: clipboard 복사 기능 추가
  src/pages/LinkPage/index.tsx
  src/utils/clipboard.ts
  src/utils/index.ts
Labels: feat

#15 feat: 404페이지 추가
  src/App.tsx
  src/pages/DetailPage/index.tsx
  src/pages/NotFound/index.tsx
Labels: feat

#16 refactor: utils함수 수정
  src/utils/formatData.ts
  src/utils/index.ts
Labels: feat, refactor

#17 refactor: 1초마다 현재 시간을 업데이트하는 로직 수정
  src/App.tsx
  src/pages/LinkPage/TimeCell.tsx
  src/pages/LinkPage/index.tsx
  src/utils/clipboard.ts
Labels: refactor

#18 feat: DetailPage 날짜생성 함수 추가, 이미지 데이터 바인딩 / NotFound Page 추가
  src/App.tsx
  src/pages/DetailPage/index.tsx
  src/pages/ErrorPage/NotData.tsx
  src/pages/ErrorPage/NotPage.tsx
  src/pages/ErrorPage/index.ts
  src/pages/LinkPage/index.tsx
  src/utils/formatData.ts
Labels: feat

#19 feat: 파일이 만료되면 파일목록, 다운로드 비활성화
  src/App.tsx
  src/pages/DetailPage/index.tsx
  src/pages/LinkPage/index.tsx
  src/utils/formatData.ts
Labels: feat

#20 Deploy: dev-branch to master-branch
  package-lock.json
  package.json
  src/App.tsx
  src/pages/DetailPage/index.tsx
  src/pages/ErrorPage/NotData.tsx
  src/pages/ErrorPage/NotPage.tsx
  src/pages/ErrorPage/index.ts
  src/pages/LinkPage/index.tsx
  src/types/apiDataType.ts
  src/types/index.ts
  src/utils/apiData.ts
  src/utils/clipboard.ts
  src/utils/formatData.ts
  src/utils/index.ts
  src/utils/sessionStorage.ts
  yarn.lock
Labels: deploy

#21 feat: netlify 배포를 위한 url, netlfy 설정 추가
  netlify.toml
  package.json
  src/App.tsx
  src/pages/DetailPage/index.tsx
  src/pages/LinkPage/index.tsx
Labels: feat

#22 chore: favicon변경, 타이틀 변경
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: chore

#23 docs: README.md update
  README.md
  public/screenshot/404.png
  public/screenshot/500.png
  public/screenshot/스크린샷 2022-02-25 오후 10.11.44.png
Labels: docs
